In [8]:
import numpy as np
world_alcohol = numpy.genfromtxt('world_alcohol.txt', delimiter=',', dtype=str)
print(world_alcohol)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [7]:
array = numpy.array([1,2,3,4])
matrix = numpy.array([[1,3,4], [2,3,5],[3,5,6]])
print(array)
print(matrix.shape)
print(matrix)

[1 2 3 4]
(3, 3)
[[1 3 4]
 [2 3 5]
 [3 5 6]]


In [11]:
students = np.genfromtxt('test.csv', delimiter=',', dtype=str, skip_header=1)
print(students)

[['adam' '18' 'Male']
 ['coco' '19' 'Female']
 ['lily' '20' 'Female']]
